# vim:ft=yaml.ansible
---
- name: Uninstall conflicting packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker.io
    - docker-compose
    - docker-compose-v2
    - docker-doc
    - podman-docker
    - containerd
    - runc
- name: Add Docker GPG apt key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: "0644"
- name: Add Docker repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.sources
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: {{ ansible_facts['distribution_release'] }}
      Components: stable
      Signed-By: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: "0644"
- name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
- name: Start nginx systemd units
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - docker.socket
- name: "Add {{ user }} to docker group"
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true
- name: Copy Docker scripts
  ansible.builtin.copy:
    src: usr/
    dest: /usr/
    owner: root
    group: root
    mode: "0755"
- name: Add cronjob that cleans up docker weekly
  ansible.builtin.cron:
    name: Cleanup docker
    special_time: weekly
    job: "/usr/local/bin/docker-clean"
    user: root
- name: Copy Docker compose files
  ansible.builtin.copy:
    src: home/user/
    dest: "/home/{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: preserve
- name: Run watchtower container
  community.docker.docker_compose_v2:
    project_src: "/home/{{ user }}/docker/watchtower/"
