# vim:ft=yaml.ansible
---
- name: Copy script
  ansible.builtin.copy:
    src: tmp/check
    dest: /tmp/check
    owner: root
    group: root
    mode: "0755"
- name: Check if kernel supports Xanmod kernel
  ansible.builtin.command: bash /tmp/check
  register: xanmod_kernel
- name: Add Xanmod GPG apt key
  ansible.builtin.get_url:
    url: https://dl.xanmod.org/archive.key
    dest: /etc/apt/keyrings/xanmod.asc
    owner: root
    group: root
    mode: "0644"
- name: Add Xanmod repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/xanmod.sources
    content: |
      Types: deb
      URIs: http://deb.xanmod.org
      Suites: {{ ansible_facts['distribution_release'] }}
      Components: main
      Signed-By: /etc/apt/keyrings/xanmod.asc
    owner: root
    group: root
    mode: "0644"
- name: Install Xanmod kernel
  ansible.builtin.apt:
    name: "{{ xanmod_kernel.stdout }}"
    state: present
    update_cache: true
  notify:
    - update_grub
    - reboot
