#!/bin/bash
# vim:ft=bash
# Function that displays error messages
function error() {
  local MESSAGE="$1"
  # Check if stderr is in interactive mode
  if [[ -t 2 ]]; then
    >&2 printf "%b\n" "\033[01;31mERROR\033[0m: $MESSAGE"
  else
    >&2 printf "%s\n" "ERROR: $MESSAGE"
  fi
  exit 1
}

# Function that displays info messages
function info() {
  local MESSAGE="$1"
  # Check if stdout is in interactive mode
  if [[ -t 1 ]]; then
    printf "%b\n" "\033[01;34mINFO\033[0m: $MESSAGE"
  else
    printf "%s\n" "INFO: $MESSAGE"
  fi
}

# Check if the script is run as root
function checkRoot() {
  if ((EUID != 0)); then
    error "Please run this script as root"
  fi
}

# Stop nginx
function startNginx() {
  systemctl start nginx.service
}

# Main function
function main() {
  checkRoot
  startNginx
}

# Stop script execution immediately
# If any command below fails
set -o "errexit"
# Throw an error if script fails
trap "error 'Something went wrong...'" EXIT

# Execute main function
main "$@"

# Disable trap
trap "" EXIT
