server:
  # Listen these interfaces and ports
  interface: ::1@53
  interface: 127.0.0.1@53

  # Strip away these IP adresses from DNS answers to protect against DNS rebinding attacks
  private-address: 10.0.0.0/8
  private-address: 172.16.0.0/12
  private-address: 192.168.0.0/16
  private-address: 169.254.0.0/16
  private-address: 127.0.0.0/8
  private-address: ::1/128
  private-address: ::ffff:0:0/96
  private-address: fd00::/8
  private-address: fe80::/10

  # Hide user agent
  hide-http-user-agent: yes

  # Refuse 'id.server' and 'hostname.bind' queries
  hide-identity: yes

  # Refuse 'version.server' and 'version.bind' queries
  hide-version: yes

  # Refuse 'trustanchor.unbound' queries
  hide-trustanchor: yes

  # Do not fall-back to sending full QNAME to potentially broken nameservers (might break things)
  qname-minimisation-strict: yes

  # Harden against algorithm downgrade when multiple algorithms are advertised in the DS record
  harden-algo-downgrade: yes

  # Harden against unknown records in the authority section and additional section
  harden-unknown-additional: yes

  # Deny queries of type ANY with an empty response
  deny-any: yes

  # Use 0x20-encoded random bits in the query to foil spoof attempts (known to cause DNSSEC issues sometimes)
  use-caps-for-id: yes

  # Set maximum receive socket buffer size to 4 MB
  so-rcvbuf: 4M

  # Set maximum send socket buffer size to 4 MB
  so-sndbuf: 4M

  # Time to live minimum for RRsets and messages in the cache
  cache-min-ttl: 450

  # Disable subnetcache module
  module-config: "validator iterator"

  # Unbound attempts to serve old responses from cache
  serve-expired: yes

  # Perform prefetching of almost expired message cache entries
  prefetch: yes

  # Perform key lookups adjacent to normal lookups
  prefetch-key: yes

  # Read the root hints from this file
  root-hints: "/usr/share/dns/root.hints"

  # File with trusted keys for validation (for DNSSEC)
  trust-anchor-file: "/usr/share/dns/root.key"

  # Add system certs to the cert bundle (for DoT)
  tls-system-cert: yes

forward-zone:
  # Forward all DNS queries to this zone
  name: "."

  # Enable DoT
  forward-tls-upstream: yes

  # IP addresses and servers to forward to
  # Cloudflare
  # forward-addr: 1.1.1.1@853#cloudflare-dns.com
  # forward-addr: 1.0.0.1@853#cloudflare-dns.com
  # forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
  # forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com

  # Cloudflare security
  forward-addr: 1.1.1.2@853#security.cloudflare-dns.com
  forward-addr: 1.0.0.2@853#security.cloudflare-dns.com
  forward-addr: 2606:4700:4700::1112@853#security.cloudflare-dns.com
  forward-addr: 2606:4700:4700::1002@853#security.cloudflare-dns.com

  # Cloudflare family
  # forward-addr: 1.1.1.3@853#family.cloudflare-dns.com
  # forward-addr: 1.0.0.3@853#family.cloudflare-dns.com
  # forward-addr: 2606:4700:4700::1113@853#family.cloudflare-dns.com
  # forward-addr: 2606:4700:4700::1003@853#family.cloudflare-dns.com

  # Google
  # forward-addr: 8.8.8.8@853#dns.google
  # forward-addr: 8.8.4.4@853#dns.google
  # forward-addr: 2001:4860:4860::8888@853#dns.google
  # forward-addr: 2001:4860:4860::8844@853#dns.google

  # Yandex
  # forward-addr: 77.88.8.8@853#common.dot.dns.yandex.net
  # forward-addr: 77.88.8.1@853#common.dot.dns.yandex.net
  # forward-addr: 2a02:6b8::feed:0ff@853#common.dot.dns.yandex.net
  # forward-addr: 2a02:6b8:0:1::feed:0ff@853#common.dot.dns.yandex.net
