# Disable vivid driver
install vivid /bin/true

# Disable CD-ROM driver
install cdrom /bin/true
install sr_mod /bin/true

# Disable floppy disk driver
install floppy /bin/true

# Disable iptables driver
install ip_tables /bin/true

# Disablbe obscure networking protocols
install dccp /bin/true
install sctp /bin/true
install rds /bin/true
install tipc /bin/true
install n-hdlc /bin/true
install ax25 /bin/true
install netrom /bin/true
install x25 /bin/true
install rose /bin/true
install decnet /bin/true
install econet /bin/true
install af_802154 /bin/true
install ipx /bin/true
install appletalk /bin/true
install psnap /bin/true
install p8023 /bin/true
install p8022 /bin/true
install can /bin/true
install atm /bin/true

# Disable obscure filesystems
install cramfs /bin/true
install freevxfs /bin/true
install jffs2 /bin/true
install hfs /bin/true
install hfsplus /bin/true
install squashfs /bin/true
install udf /bin/true
install cifs /bin/true
install nfs /bin/true
install nfsv3 /bin/true
install nfsv4 /bin/true
install ksmbd /bin/true
install gfs2 /bin/true
install reiserfs /bin/true
install kafs /bin/true
install orangefs /bin/true
install 9p /bin/true
install adfs /bin/true
install affs /bin/true
install afs /bin/true
install befs /bin/true
install ceph /bin/true
install coda /bin/true
install ecryptfs /bin/true
install jfs /bin/true
install minix /bin/true
install nilfs2 /bin/true
install ocfs2 /bin/true
install romfs /bin/true
install ubifs /bin/true
install zonefs /bin/true
install sysv /bin/true
install ufs /bin/true

# Disable GNSS
install gnss /bin/true
install gnss-mtk /bin/true
install gnss-serial /bin/true
install gnss-sirf /bin/true
install gnss-usb /bin/true
install gnss-ubx /bin/true

# Disable Firewire and Thunderbolt
install firewire-core /bin/true
install firewire_core /bin/true
install firewire-ohci /bin/true
install firewire_ohci /bin/true
install firewire_sbp2 /bin/true
install firewire-sbp2 /bin/true
install firewire-net /bin/true
install thunderbolt /bin/true
install ohci1394 /bin/true
install sbp2 /bin/true
install dv1394 /bin/true
install raw1394 /bin/true
install video1394 /bin/true
