# vim:ft=yaml.ansible
---
- name: Add nginx GPG apt key
  ansible.builtin.get_url:
    url: https://nginx.org/keys/nginx_signing.key
    dest: /etc/apt/keyrings/nginx.asc
    owner: root
    group: root
    mode: "0644"
- name: Add nginx repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/nginx.sources
    content: |
      Types: deb
      URIs: https://nginx.org/packages/ubuntu
      Suites: {{ ansible_facts['distribution_release'] }}
      Components: nginx
      Signed-By: /etc/apt/keyrings/nginx.asc
    owner: root
    group: root
    mode: "0644"
- name: Install nginx and certbot
  ansible.builtin.apt:
    name:
      - nginx
      - certbot
    state: present
    update_cache: true
- name: Copy nginx template
  ansible.builtin.template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
- name: "Create {{ domain }} directory"
  ansible.builtin.file:
    path: "/var/nginx/{{ domain }}/"
    owner: nginx
    group: nginx
    mode: "0755"
    state: directory
- name: Find all files inside /etc/nginx/conf.d/
  ansible.builtin.find:
    paths: /etc/nginx/conf.d/
    file_type: any
  register: configs
- name: Remove all files from that directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ configs.files }}"
- name: Copy fail2ban nginx config
  ansible.builtin.copy:
    src: etc/fail2ban/
    dest: /etc/fail2ban/
    owner: root
    group: root
    mode: preserve
  notify: restart_fail2ban
- name: Copy certbot hooks
  ansible.builtin.copy:
    src: etc/letsencrypt/
    dest: /etc/letsencrypt/
    owner: root
    group: root
    mode: "755"
- name: "Obtain certificate for {{ domain }}"
  ansible.builtin.command:
    cmd: "certbot certonly --standalone --non-interactive --agree-tos --register-unsafely-without-email --pre-hook /etc/letsencrypt/renewal-hooks/pre/stop-nginx --post-hook /etc/letsencrypt/renewal-hooks/post/start-nginx --disable-hook-validation -d {{ domain }}"
- name: Add cronjob that renews certificate weekly
  ansible.builtin.cron:
    name: "Renew {{ domain }} certificate"
    special_time: weekly
    job: /usr/bin/certbot renew --pre-hook /etc/letsencrypt/renewal-hooks/pre/stop-nginx --post-hook /etc/letsencrypt/renewal-hooks/post/start-nginx --disable-hook-validation
    user: root
- name: Ensure nginx service is enabled
  ansible.builtin.systemd_service:
    name: nginx.service
    enabled: true
    state: started
